package permission

// Los códigos de módulo y submódulo coinciden con los paquetes de Go
// (internal/erp/catalog/products → erp.catalog.products) y las etiquetas con el
// menú del frontend.
func erp() System {
	return sys("erp", "ERP",
		mod("catalog", "Catálogo y maestros",
			sub("products", "Productos", Create, Edit, Delete, Export),
			sub("units", "Unidades y presentaciones", Create, Edit, Delete),
			sub("partners", "Proveedores y clientes", Create, Edit, Delete),
			sub("branches", "Sucursales y almacenes", Create, Edit, Delete),
			sub("price_lists", "Listas de precios", Create, Edit, Delete, Publish),
		),
		mod("inventory", "Inventario",
			sub("stock", "Stock por sucursal y lote", Export),
			sub("kardex", "Kardex valorizado", Export),
			sub("expiry", "Control de vencimientos", Resolve),
			sub("transfers", "Transferencias", Request, Approve, Send, Receive, Cancel),
			sub("adjustments", "Ajustes y mermas", Create, Approve),
			sub("cycle_count", "Inventario cíclico", Schedule, Register, Approve),
		),
		mod("purchasing", "Compras",
			sub("requirements", "Requerimientos", Create, Edit, Delete, Approve),
			sub("quotes", "Cotizaciones", Create, Edit, Delete, Approve),
			sub("purchase_orders", "Órdenes de compra", Create, Edit, Approve, Send, Cancel),
			sub("receipts", "Recepción de mercadería", Register, Cancel),
			sub("supplier_returns", "Devoluciones a proveedor", Create, Approve, Cancel),
			sub("costing", "Costeo", Calculate, Adjust),
		),
		mod("sales", "Ventas y distribución",
			sub("wholesale", "Ventas mayoristas", Create, Edit, Cancel),
			sub("quotes_orders", "Cotizaciones y pedidos", Create, Edit, Approve, Cancel),
			sub("dispatch_guides", "Guías de remisión", Generate, Send, Cancel),
			sub("receivables", "Cuentas por cobrar", RegisterPayment, Export),
		),
		mod("finance", "Finanzas y contabilidad",
			sub("ledger", "Contabilidad general", Register, Edit, Close, Export),
			sub("payables", "Cuentas por pagar", Register, RegisterPayment, Approve),
			sub("treasury", "Tesorería y bancos", Register, Approve),
			sub("bank_reconciliation", "Conciliación bancaria", Reconcile),
			sub("cost_centers", "Centros de costo", Create, Edit, Delete),
			sub("tax_books", "Libros electrónicos e impuestos", Generate, Export, Send),
		),
		mod("fixed_assets", "Activos fijos",
			sub("asset_register", "Registro de activos", Create, Edit, Delete),
			sub("depreciation", "Depreciación", Calculate, Approve),
			sub("maintenance", "Mantenimiento", Schedule, Register),
		),
		mod("administration", "Administración del sistema",
			sub("multicompany", "Multiempresa y multisucursal", Create, Edit),
			sub("roles_audit", "Roles y auditoría", Edit),
			sub("integrations", "Integraciones", Edit, Test),
		),
	)
}

func pos() System {
	return sys("pos", "POS",
		mod("sales", "Ventas",
			sub("quick_sale", "Venta rápida", Register, Discount),
			sub("customer_sale", "Venta con cliente", Register, Discount),
			sub("credit_sale", "Venta a crédito", Register, Approve),
			sub("held_sales", "Ventas en espera", Resume, Cancel),
		),
		mod("billing", "Facturación electrónica",
			sub("documents", "Comprobantes", Export),
			sub("sunat_submission", "Envío a SUNAT", Send, Resend),
			sub("contingency", "Contingencia y reenvío", Resend, Resolve),
		),
		mod("cash", "Caja",
			sub("open_close", "Apertura y cierre", Open, Close),
			sub("count", "Arqueo", Register, Approve),
			sub("movements", "Ingresos y retiros", Register, Approve),
			sub("shift_close", "Cierre por turno", Close),
		),
		mod("payment_methods", "Medios de pago",
			sub("cash_cards", "Efectivo y tarjetas", Edit),
			sub("digital_wallets", "Yape y Plin", Edit),
			sub("mixed", "Pago mixto", Edit),
			sub("reconciliation", "Conciliación por medio", Reconcile, Export),
		),
		mod("promotions", "Promociones y precios",
			sub("discounts", "Descuentos y combos", Create, Edit, Delete, Publish),
			sub("branch_prices", "Precios por sucursal", Edit, Publish),
			sub("coupons", "Cupones", Create, Edit, Delete, Generate),
		),
		mod("returns", "Devoluciones y anulaciones",
			sub("credit_notes", "Devolución con nota de crédito", Register, Approve),
			sub("cancellations", "Anulación con autorización", Request, Approve),
		),
		mod("security", "Seguridad y configuración",
			sub("users_roles", "Usuarios y roles", Assign),
			sub("terminals", "Terminales y series", Create, Edit),
			sub("offline", "Modo offline", Edit),
		),
	)
}
