package permission

func scm() System {
	return sys("scm", "SCM",
		mod("demand", "Planeación de la demanda",
			sub("forecast", "Pronóstico por SKU", Generate, Adjust),
			sub("seasonality", "Estacionalidad y eventos", Create, Edit, Delete),
			sub("abc", "Rotación ABC", Calculate),
		),
		mod("replenishment", "Reposición",
			sub("min_max", "Stock mínimo y máximo", Edit),
			sub("suggested_order", "Pedido sugerido por tienda", Generate, Approve),
			sub("stockout_alerts", "Alertas de quiebre", Edit),
		),
		mod("sourcing", "Abastecimiento",
			sub("supplier_orders", "Pedido sugerido a proveedores", Generate, Approve),
			sub("lead_times", "Lead times", Edit),
			sub("supplier_rating", "Evaluación de proveedores", Evaluate),
		),
		mod("distribution", "Distribución y transporte",
			sub("routes", "Rutas y despachos", Create, Edit, Schedule, Cancel),
			sub("fleet", "Flota y transportistas", Create, Edit, Delete),
			sub("tracking", "Seguimiento de entregas", Register),
			sub("logistics_costs", "Costos logísticos", Register, Export),
		),
		mod("quality", "Control de mermas y calidad",
			sub("waste_by_cause", "Mermas por causa", Register),
			sub("expiring", "Productos por vencer", Resolve),
			sub("supplier_claims", "Reclamos a proveedores", Create, Send, Resolve),
		),
	)
}

func wms() System {
	return sys("wms", "WMS",
		mod("structure", "Estructura del almacén",
			sub("locations", "Zonas, pasillos y ubicaciones", Create, Edit, Delete),
			sub("capacities", "Capacidades y tipos", Edit),
		),
		mod("receiving", "Recepción",
			sub("appointments", "Citas de recepción", Schedule, Cancel),
			sub("po_verification", "Verificación contra orden de compra", Confirm),
			sub("lot_labeling", "Etiquetado de lote y vencimiento", Generate),
		),
		mod("storage", "Almacenamiento",
			sub("suggested_location", "Ubicación sugerida", Assign),
			sub("relocations", "Reubicaciones", Create, Confirm),
			sub("location_stock", "Stock por ubicación", Export),
		),
		mod("picking", "Picking",
			sub("orders_waves", "Por orden, ola o ruta", Generate, Assign, Confirm),
			sub("handheld", "Con handheld o scanner", Confirm),
			sub("pick_replenishment", "Reposición de zona de picking", Request, Confirm),
		),
		mod("packing", "Packing y despacho",
			sub("consolidation", "Consolidación por tienda", Confirm),
			sub("dispatch_guides", "Guías de remisión", Generate, Send, Cancel),
			sub("vehicle_loading", "Carga y salida de vehículos", Confirm),
		),
		mod("inventories", "Inventarios",
			sub("cycle_counts", "Conteos cíclicos", Schedule, Register),
			sub("reconciliation", "Conciliación y ajustes", Reconcile, Adjust, Approve),
		),
		mod("reverse_logistics", "Devoluciones (logística inversa)",
			sub("store_returns", "Retorno desde tiendas", Receive),
			sub("classification", "Clasificación", Register),
		),
	)
}
