package permission

func hcm() System {
	return sys("hcm", "RR.HH.",
		mod("personnel", "Administración de personal",
			sub("files", "Legajo y contratos", Create, Edit, Delete),
			sub("structure", "Estructura y puestos", Create, Edit, Delete),
			sub("t_registro", "T-Registro", Send, Export),
		),
		mod("attendance", "Asistencia y turnos",
			sub("clocking", "Marcación", Register),
			sub("shifts", "Turnos por tienda", Create, Edit, Schedule, Publish),
			sub("overtime", "Horas extra, tardanzas y faltas", Approve),
			sub("leaves", "Permisos y licencias", Request, Approve),
		),
		mod("payroll", "Planilla",
			sub("remuneration", "Remuneraciones y descuentos", Edit, Calculate, Approve),
			sub("benefits", "Gratificaciones, CTS y vacaciones", Calculate, Approve),
			sub("plame", "PLAME, AFP/ONP y EsSalud", Generate, Export, Send),
			sub("payslips", "Boletas de pago", Generate, Send),
			sub("settlements", "Liquidaciones", Calculate, Approve),
		),
		mod("compensation", "Compensaciones y desempeño",
			sub("commissions", "Comisiones y bonos", Calculate, Approve),
			sub("performance", "Evaluación de desempeño", Evaluate, Approve),
		),
		mod("recruiting", "Reclutamiento y capacitación",
			sub("vacancies", "Vacantes y postulantes", Create, Edit, Delete),
			sub("onboarding", "Onboarding", Assign, Confirm),
			sub("training", "Capacitaciones y certificaciones", Schedule, Register),
		),
		mod("occupational_health", "Seguridad y salud ocupacional",
			sub("medical_exams", "Exámenes médicos", Schedule, Register),
			sub("incidents", "Incidentes y accidentes", Register, Resolve),
			sub("ppe", "Entrega de EPP y uniformes", Register),
		),
	)
}

func crm() System {
	return sys("crm", "CRM",
		mod("customers", "Clientes",
			sub("base", "Base única de clientes", Create, Edit, Delete, Export),
			sub("segmentation", "Segmentación", Create, Edit, Delete),
			sub("history", "Historial de compras", Export),
		),
		mod("loyalty", "Programa de puntos",
			sub("points", "Acumulación y canje", Adjust),
			sub("tiers", "Niveles y beneficios", Create, Edit, Delete),
			sub("identification", "Identificación por DNI o celular", Edit),
		),
		mod("campaigns", "Campañas",
			sub("coupons", "Cupones segmentados", Create, Edit, Delete, Send),
			sub("messaging", "WhatsApp, SMS y email", Create, Schedule, Send, Cancel),
			sub("behavior_promos", "Promociones por comportamiento", Create, Edit, Publish),
		),
		mod("service", "Atención al cliente",
			sub("complaints", "Reclamos y libro de reclamaciones", Register, Resolve),
			sub("surveys", "Encuestas de satisfacción", Create, Send),
		),
	)
}
